version: "3"
services:
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - server

  server:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8090:8090"
    depends_on:
    
      - mongodb
    environment:
      - PORT=8090
      - DB_URL=mongodb://mongodb:27017/Services

  mongodb:
    image: mongo
    ports:
      - "27017:27017"
